included_labels = {
  'finger/spin': ['position_0', 'position_1', 'position_2', 'position_3'],
    'point_mass/easy': ['position_0', 'position_1'],
    'pendulum/swingup': ['orientation_0', 'orientation_1'],
    'ball_in_cup/catch': ['position_0', 'position_1', 'position_2', 'position_3'],
    'reacher/hard': ['position_0', 'position_1'],
    'manipulator/bring_ball': ['arm_pos_0', 'arm_pos_1',
                               'arm_pos_2', 'arm_pos_3',
                               'arm_pos_4', 'arm_pos_5',
                               'arm_pos_6', 'arm_pos_7',
                               'arm_pos_8', 'arm_pos_9',
                               'arm_pos_10', 'arm_pos_11',
                               'arm_pos_12', 'arm_pos_13',
                               'arm_pos_14', 'arm_pos_15',
                               'hand_pos_0', 'hand_pos_1',
                               'hand_pos_2', 'hand_pos_3',
                               'object_pos_0', 'object_pos_1',
                               'object_pos_2', 'object_pos_3'],
    'cartpole/balance': ['position_0', 'position_1', 'position_2'],
    'bowling': ['ball_x', 'ball_y', 'player_x', 'player_y'], 
    'boxing': ['player_x', 'player_y', 'enemy_x', 'enemy_y'], 
    'breakout': ['player_x', 'ball_x', 'ball_y'], 
    'frostbite': ['player_x', 'player_y'], 
    'montezuma_revenge': ['player_x', 'player_y'],
    'ms_pacman': ['player_x', 'player_y'], 
    'pitfall': ['player_x', 'player_y'], 
    'pong': ['ball_x', 'ball_y', 'enemy_y', 'player_y'], 
    'private_eye': ['player_x', 'player_y'], 
    'qbert': ['player_x', 'player_y'],
    'riverraid': ['player_x'], 
    'seaquest': ['player_x', 'player_y'], 
    'skiing': ['player_x', 'object_y_0'], 
    'tennis': ['player_x', 'player_y', 'enemy_x', 'enemy_y', 'ball_x', 'ball_y'], 
}